services:
  frontend:
    build:
      context: .
      dockerfile: vite-front/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - ./certs:/certs:ro
