services:
  backend:
    container_name: express-backend
    build: .
    command: sh -c "node init/seed.js && npm start"
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/iothink
      - TELEGRAPH_API_KEY=${TELEGRAPH_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./certs:/certs:ro
    networks:
      - iot-network
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
    networks:
      - iot-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  iot-network:
    driver: bridge
