services:
  backend:
    container_name: express-backend
    build: .
    command: sh -c "node init/seed.js && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/iothink
      - TELEGRAPH_API_KEY=${TELEGRAPH_API_KEY}
    volumes:
      - ./certs:/certs:ro
    networks:
      - iot-network
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - iot-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  iot-network:
    driver: bridge
