version: '3.8'

services:
  mqtt-auth-backend:
    container_name: mqtt-auth-backend
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    restart: unless-stopped
