services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "8883:8883"   # port MQTT sécurisé par SSL/TLS
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped

networks:
  default:
    name: mqtt-network
